# fly.toml app configuration file generated for contact-hub
app = "contact-hub"
primary_region = "ams"

[build]
  # Удаляем строку с image, чтобы fly.io самостоятельно собрал образ из Dockerfile

[env]
  PORT = "8080"
  DOCKER_ENV = "true"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024